### ISSUE TITLE
Unable to build the project without errors

### ISSUE THREAD

**Issue by just-a-bad-day** [dc8044/sublime-megre-keygen#1]
Hi and thanks for this project.

I tried to follow the instructions but I get errors during the last step.

#### Step 1

Output for `cmake .. -G "Visual Studio 16 2019" -A Win32`:
```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The CXX compiler identification is MSVC 19.27.29111.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is MSVC 19.27.29111.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.27.29110/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Failed
-- Performing Test COMPILER_HAS_DEPRECATED
-- Performing Test COMPILER_HAS_DEPRECATED - Success
-- Setting build type to 'Release' as none was specified.
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/xxx/Desktop/sublime-megre-keygen/build
```
(Seems ok so far)

#### Step 2

But then lots of errors appear near the end when I run `cmake --build . --target ALL_BUILD --config RelWithDebInfo`:
(I put the log in a gist because it's huge)
~https://gist.github.com/just-a-bad-day/0a26c826a4ac158e31e5535a529364ef#file-build-log-L1200~

If you have any idea why this happens I'd really appreciate it.

## Versions

- Windows 10
- cmake 3.18.2

<details><summary>Visual Studio + Installed products</summary><pre>Microsoft Visual Studio Community 2019
Version 16.7.2
VisualStudio.16.Release / 16.7.2 + 30413.136
Microsoft.NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019 00435 - 60000 - 00000 - AA474<br>Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019 16.7.532.28833<br>ASP.NET and Web Tools 2019

C# Tools 3.7.0 - 6.20412.3 + d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878<br>C# components used in the IDE.Depending on your project type and settings, a different version of the compiler may be used.

IntelliCode Extension 1.0<br>IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger 1.0<br>Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI - Based Debugger 1.0<br>Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards 1.0<br>Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package 1.0<br>Microsoft Visual Studio VC Package

NuGet Package Manager 5.7.0<br>NuGet Package Manager in Visual Studio.For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension 1.0<br>ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test 1.0<br>Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test 1.0<br>Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Visual Basic Tools 3.7.0 - 6.20412.3 + d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878<br>Visual Basic components used in the IDE.Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package 1.0<br>Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake 1.0<br>Visual Studio Tools for CMake</pre></details>

**Comment by phracker** [comment]
I had a similar issue. Modify pelib/include/pelib/PeLibAux.h and add:

```
#include <fstream>
#include <string>
```
after line #17, `#include <limits>`.

Save and rebuild.

**Comment by just-a-bad-day** [comment]
Thanks @phracker! That seems to have fixed the errors.

Now I have another question, what to do when the build finishes? I'm kind of a noob with this stuff, I thought there would be an exe to run but I don't see anything. Do I have to run something inside Visual Studio?

Thanks again for the help.

**EDIT:** Nevermind, I read the logs more carefully and saw the output path  
`sublime-megre-keygen\build\src\RelWithDebInfo\Generator.exe`

**Comment by kevindevm** [comment]
@just-a-bad-day @phracker 
with what version of sublime ~~merge~~ megre works?
